name=input("Enter your name ")
branch=input("Enter your branch ")
gender=input("Enter your gender ")
college=input("Enter your college ")
age=int(input("Enter your age "))
print("Your name is ", name)
print("Your branch is ", branch)
print("Your gender is ",gender)
print("Your college is ",college)
print("Your age is ",age)
